version: '3.8'

services:
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tezirek-tamaq
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tezirek-tamaq"]
      interval: 3s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    environment:
      - POSTGRES_DSN=postgres://postgres:postgres@db:5432/marketplace?sslmode=disable
      - APP_PORT=50051
    ports:
      - "50051:50051"
    depends_on:
      db:
        condition: service_healthy

  restaurant-service:
    build:
      context: ./restaurant-service
    container_name: restaurant-service
    environment:
      - POSTGRES_DSN=postgres://postgres:postgres@db:5432/marketplace?sslmode=disable
      - APP_PORT=50053
    ports:
      - "50053:50053"
    depends_on:
      db:
        condition: service_healthy

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    environment:
      - POSTGRES_DSN=postgres://postgres:postgres@db:5432/marketplace?sslmode=disable
      - APP_PORT=50052
    ports:
      - "50052:50052"
    depends_on:
      db:
        condition: service_healthy

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - USER_GRPC_ADDR=user-service:9000
      - REST_GRPC_ADDR=restaurant-service:9001
      - ORDER_GRPC_ADDR=order-service:9002
      - APP_PORT=8080
    depends_on:
      - user-service
      - restaurant-service
      - order-service

volumes:
  db_data:
